services:
  sanity:
    image: sanity
    build: ./api
    ports:
      - "3333:3333"
    volumes:
      - ./schemas:/api/schemas
      - remove_client:/api/node_modules
  svelte:
    image: svelte
    build: ./test
    ports:
      - "5173:5173"
    volumes:
      - ./src:/work/src
      - remove_server:/work/node_modules
    depends_on:
      - sanity

volumes:
  remove_client:
    driver: 'local'
  remove_server:
    driver: 'local'