services:
  sanity:
    image: sanity
    build: ./api
    ports:
      - "3333:3333"
    volumes:
      - ./api/node_modules:/api/node_modules
      - ./api/schemas:/api/schemas
  svelte:
    image: svelte
    build: ./test
    ports:
      - "5173:5173"
    volumes:
      - ./test/node_modules:/work/node_modules
      - ./test/src:/work/src
    depends_on:
      - sanity